### PR TITLE
Push login group loading to sync task

### PR DESCRIPTION
**Pull request by suirad**
This should give a speed increase to logins. It will put group loading on the next tick.

### CODE REVIEW

**Comment by Maxopoly** [comment]
You can actually remove that completly. It's a leftover from reinforcement decay (which was initially in NameLayer) and there is no good reason to preload all groups of a player.

**Comment by suirad** [comment]
Works for me. I'll swap it when I get back from getting food.

**Comment by ttk2** [comment]
So now we can just check for player group existence on first login and otherwise not touch groups on login?

**Comment by suirad** [comment]
Yes since they get loaded on first use and then cached

**Comment by suirad** [comment]
Update commit, should be good to merge.

**Pull request merged**
