### PR TITLE
Re-added Group Reinforcement Count

### PR DESCRIPTION
**Pull request by clone2204**
Changes to Namelayer plugin, Citadel Changes also required.

These changes allow for groups to keep track of how many reinforcements
of each type are under that group. The groups will now keep track of the
number, and now only incriment or decriment from that number when a
reinforcement is added or removed from the DB.

### CODE REVIEW

**Comment by rourke750** [comment]
Are you forgetting code and this is incredibly limited.

**Comment by clone2204** [comment]
There are two pull requests, this one required changes to both namelayer and citadel.

**Comment by rourke750** [comment]
You can't put citadel code in NameLayer.

**Comment by clone2204** [comment]
I didn't. Namelayer keeps track of the amount of reinforcements at the group level, and citadel just calls a method that increments or decrements the count.

**Comment by erocs** [comment]
NameLayer shouldn't know about reinforcements. Keep it in Citadel.

**Comment by erocs** [comment]
Or create a generic statistic layer for groups in NameLayer.

**Comment by rourke750** [comment]
NameLayer doesn't keep track of anything Citadel related.  All the counting of Reinforcements is in Citadel.

**Comment by clone2204** [comment]
I think it is going to need to be done in namelayer. From what I gathered, citadel does not look at reinforcements from an overall group view, but instead just looks at them as individual reinforcements. Namelayer seems to be the one to keep track of things at a group level, which is where any sort of group reinforcement count needs to be kept.

**Comment by rourke750** [comment]
So youre telling me that this method here: https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/database/CitadelReinforcementData.java#L595 in citadel that counts the amount of reinforcements in a group doesn't exist?

**Pull request closed without merging**
