### PR TITLE
Added method for improved InfoDump command

### PR DESCRIPTION
**Pull request by clone2204**
Will make another pull making change for InfoDump command, because bad at github.

### CODE REVIEW

**Comment by WildWeazel** [comment]
ok to test

I'm not sure how big that perms list can get, but it's usually a good idea to use StringBuilder in cases like that.

**Comment by rourke750** [comment]
I don't see a point for this pull request.

**Comment by clone2204** [comment]
I just made another method to list the perms, this one just leaves off the "The perms are", with makes things more difficult.

**Comment by rourke750** [comment]
This isnt really necessary though...  What would this be used for?

**Comment by clone2204** [comment]
The same thing that I made a pull request removing a semi-colon was for. Its just formatting for the NamelayerGUI.

**Comment by rourke750** [comment]
You can do formatting client side this isn't really needed.

**Comment by clone2204** [comment]
Not this time. I can't deal with the colon in it, I use it as a delimiter.

**Comment by ttk2** [comment]
Then pick another delimiter.

**Comment by rourke750** [comment]
Or just discard the first part of it.

**Comment by jjj5311** [comment]
if you cant handle that first part just get a substring after the first
colon and then do your parsing

**Pull request closed without merging**
