### PR TITLE
Add aliases to commands

### PR DESCRIPTION
**Pull request by suirad**
* Implements Civcraft/NameLayer/issues/14
* Added easy way to add more aliases

Check out the ones i added, let me know if there are any you want changed or added.

### CODE REVIEW

**Comment by suirad** [comment]
@rourke750 @ttk2

**Comment by rourke750** [comment]
I'm sorry you did way to much work for what you tried to do. Look at citadel you just need to add the alias stuff to the plugin.yml.

**Comment by suirad** [comment]
And here i was thinking what i did was clever

**Comment by suirad** [comment]
Whatever @rourke750 , i dont need you. Il raise my baby myself.

I'll see you in court.

**Comment by ProgrammerDan** [comment]
Paging Montel Williams!

**Comment by ttk2** [comment]
so whats the status of this pull?

**Comment by suirad** [comment]
Updated commit to only add aliases via plugin.yml

**Comment by rourke750** [comment]
Hey this is perfect thanks a bunch.

**Comment by ttk2** [comment]
is the documentation updated?

**Pull request merged**
