### PR TITLE
Fix for NPE in GroupPermissions & Fix for permissions on /nllm

### PR DESCRIPTION
**Pull request by suirad**
Fix for issue Civcraft/NameLayer#107
Fix for issue Civcraft/NameLayer#86
Example of 86

### CODE REVIEW

**Comment by ttk2** [comment]
sweet, waiting on review.. and then jenkins.

**Comment by suirad** [comment]
Added on another fix, this time its for #86

**Comment by Maxopoly** [comment]
Just 2 performance improvements, aside from that it looks good and ready for testing. @ttk2  Just throw it on civtest please for a quick test and we could roll it out tomorrow.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by suirad** [comment]
@Maxopoly Good catch. I got tunnel vision on the error itself. Check out that last commit with the optimizations you mentioned.

@rourke750 @ttk2

**Comment by Maxopoly** [comment]
Yep, looks good

**Comment by ttk2** [comment]
ok to test

**Comment by ttk2** [comment]
bah, anyways this is on Civtest.

**Comment by ttk2** [comment]
did this get tested at all?

**Comment by Maxopoly** [comment]
Me and @suirad tested the /nllm permission thing earlier and it worked (as noted on trello ;) ), the other stuff isn't something that could be tested too much, but looks pretty solid. 

@suirad said it's ready for prod, I agree with that.

**Comment by ttk2** [comment]
I just saw that on trello, cool, staging for tomorrow.

**Pull request merged**
