### PR TITLE
Making tab completes sharding friendly

### PR DESCRIPTION
**Pull request by Maxopoly**
Making this is as a pullrequest so I can make a test build. Also improves functionality for a non-sharding server.

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
@rourke750 Was I ever added to the "ok to test" listener? It choses to ignore me every time I try.

**Comment by rourke750** [comment]
try now

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
Works, thanks a lot.

**Comment by ttk2** [comment]
this good to merge?

**Comment by Maxopoly** [comment]
No, because of https://github.com/Civcraft/Mercury/issues/10

**Comment by ttk2** [comment]
ah that needs to be fixed soonish then.

**Comment by rourke750** [comment]
@Maxopoly Good now?

**Comment by Maxopoly** [comment]
Yes, btw the mercury fix also fixed another stack that kept popping up on civtest.

**Pull request merged**
