### PR TITLE
Made some minor additions to group aliases

### PR DESCRIPTION
**Pull request by Goldmattress**
Made some minor additions to group aliases, no idea how this works, tried doing what seemed useful

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
Thanks for taking a stab, Matta.

My thoughts focus more on:

What commands do players use often, and how do they think about using them?

"Namelayer" doesn't come to mind when people are, functionally, only interacting with Citadel.

Yes, philosophically they are separate, but Citadel and Namelayer are fairly tightly coupled. So, let's stop fooling ourselves.


A useful set of aliases would probably mirror citadel's command structure, or something similar.

eg:
* /nlcg == /groupcreate  /gc
* /nlip == /groupinvite   /gi
* /nlrm == /memberremove   /gmr
* /nllg == /groupdepart   /gd
* /nlagi == /groupaccept   /ga

etc.

Yes, Namelayer is a separate plugin that could be useful on its own integrated with something that isn't citadel. No, player's don't care one whit about that. 

@rourke750  thoughts?

**Comment by Maxopoly** [comment]
/gc is already an alias for /groupchat

**Comment by Goldmattress** [comment]
I like that suggestion but the impression I got from rourke is that the commands must start with /nl to guarantee that we do not clash with other plugins.

**Comment by rourke750** [comment]
Depending on the alias I think we can make exceptions.

**Comment by Maxopoly** [comment]
We should have /accept, /invite, /promote, /groups, /members

**Comment by Goldmattress** [comment]
Ok I made the suggested changes, is this ok @rourke750 ?

**Comment by rourke750** [comment]
for some of the comands you have / in them.  For those to work in game it would require //<command> so unless that was intention can your remove them.

**Comment by Maxopoly** [comment]
Replaced by https://github.com/Civcraft/NameLayer/pull/172

**Pull request closed without merging**
