### PR TITLE
Bad stuff fixxed

### PR DESCRIPTION
**Pull request by ribagi**

### CODE REVIEW

**Comment by spaceFountain** [comment]
@rourke750 this seems like it probably is actually worth doing. It will improve performance a bit at basically no cost.

**Comment by ttk2** [comment]
more descriptive description please?

**Comment by spaceFountain** [comment]
Ah yes sorry. It just replaces a use of string concatenation with a StringBuilder. I'm not sure exactly why but I understand it's better in cases such as this where there is looping as the compiler won't optimize to using one by itself. I believe using StringBuilder's are slightly more efficient in memory allocations as unlike strings it is mutable.

**Comment by jjj5311** [comment]
we should probably incorporate this into list groups as well i suppose? and any spot we are creating an output with a loop?

**Comment by WildWeazel** [comment]
I'm not sure how much the compiler will optimize this away, but it's a good habit to follow

**Pull request merged**
