### PR TITLE
Added permission for nllm command

### PR DESCRIPTION
**Pull request by TealNerd**
By default available for all permission types above member

### CODE REVIEW

**Comment by jjj5311** [comment]
this is the same with the other perms thing... someone please run the sql to update all existing groups

**Comment by ttk2** [comment]
do we have a script to run to update existing groups? a pull with a command
for that could be useful.

**Comment by jjj5311** [comment]
https://github.com/Civcraft/NameLayer/pull/72

erocs laid out the command here... Next week i will have some free time again so i will be able to check it out

**Comment by ttk2** [comment]
update permissions set tier = tier + ' GROUPSTATS' where role IN ('ADMINS',
'OWNER');

is this safe to just run? I  can do it in 30 seconds if so, need to know if
I can run it live too.

**Comment by erocs** [comment]
Might change it to:
update permissions set tier = tier + ' GROUPSTATS' where role IN ('ADMINS',
'OWNER') AND permissions NOT LIKE '%GROUPSTATS%';

Should be fine to run live. I don't know if NameLayer caches the
permissions for a group. If it does this would need to be run at restart,
which is easily doable.

**Comment by ttk2** [comment]
lets just run it at restart.

**Comment by jjj5311** [comment]
I think this pull is still valid though and should be merged to fix the list members command?

**Comment by erocs** [comment]
Looks fine. Not sure why it was closed though.

**Comment by rourke750** [comment]
Told him to make this dependent on group stats command since they are
pretty similar.

**Pull request closed without merging**
