### PR TITLE
Alert user they were added to group while they were away using Auto-accept 

### PR DESCRIPTION
**Pull request by jjj5311**
Tested this locally and it works as expected

Should take care of issue #48

### CODE REVIEW

**Comment by ttk2** [comment]
where does it store this info?

**Comment by jjj5311** [comment]
Its stored in a hashmap 

https://github.com/Civcraft/NameLayer/blob/master/src/vg/civcraft/mc/namelayer/listeners/PlayerListener.java#L20

**Comment by ttk2** [comment]
so it does not persist across restarts?

**Comment by jjj5311** [comment]
I would assume not, should probably create a persistent way to carry notifications across restarts

This hashmap takes care of all the notifications for players from namelayer when they login i believe

**Comment by ttk2** [comment]
so does it just store all group transitions that the player was not online
for during that particular session?

**Comment by jjj5311** [comment]
No only the notifications

**Comment by rourke750** [comment]
I brought this up with you.  Group invites will not persist through restart.

**Comment by rourke750** [comment]
@jjj5311 Looks pretty good.  Just AutoComplete and you didnt do Bukkit.getPlayer correctly.  Bukkit.getPlayer only returns players that are currently logged in otherwise null.  I can fix that though.

**Comment by rourke750** [comment]
@jjj5311 Oh never mind I got mixed up on variable names.  Looks good.

**Comment by jjj5311** [comment]
Cool glad I could help

**Pull request merged**
