### PR TITLE
This should work, but for some reason NameLayer isn't picking up Bukk…

### PR DESCRIPTION
**Pull request by suirad**
…it events for: PlayerJoinEvent, PlayerQuitEvent, and AsyncPluginBroadcastMessageEvent.

@rourke750, please advise. Also excuse the leftover debugging code.

Either Mercury isn't making the Event or Namelayer isn't grabbing those events. When you quote me on the commit that corrects this please so i can learn what the issue is. I very well could be missing something because i am tired...

### CODE REVIEW

**Comment by Rourke** [comment]
You've got the wrong @rourke. I can't help you.

**Comment by suirad** [comment]
Lol forgot the numbers, always with the numbers. @rourke750

**Comment by rourke750** [comment]
Lol. So what isn't happening?

**Comment by suirad** [comment]
For some reason: MercuryMessageListener.java:32 is never reached. And none of the player events in that file are filed. Even though NameLayerPlugin.java:70 goes through fine and even gets to that runnable at the bottom.

**Comment by rourke750** [comment]
It looks like NameLayer is loading before mercury. Hence why the npe with mercury and none with the delay.  Schedule the delay and put everything in the delay with everything in the if statement.

**Comment by suirad** [comment]
Lol of course. Namelayer is very unpredictable lol.  So that's why it's not hooking those events? Think that would affect the login/out events too?

**Comment by rourke750** [comment]
The class isn't be registered.  I bet if you tested ismurcury enabled it would be false.

I believe most of these methods should be moved to onload. That's for me to fix.  Just include everything in the delay to test and I'll fix it proper.

**Comment by suirad** [comment]
Alright I'll do that. Headed to bed though, so I'll make another pull tomorrow after work. Il close this.

**Comment by suirad** [comment]
Should have this and civchat ready for shard testing by end of tomorrow as long as nothing unexpected happens.

**Pull request closed without merging**
