### PR TITLE
Update InfoDump.java

### PR DESCRIPTION
**Pull request by clone2204**
I am bad at github, I am sorry.

### CODE REVIEW

**Comment by rourke750** [comment]
Anything else you want to update while you are here?

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
so should I update namlayer on Civtest with this?

**Comment by rourke750** [comment]
This isn't merged.

**Comment by ttk2** [comment]
kk

**Comment by clone2204** [comment]
Did you see the other commit I made? This one relys on that.

Sorry I am doing it like this, my personal git is still fucked up with the citadel reinforcement counting stuff I was working on.

**Pull request closed without merging**
