### PR TITLE
Maven fix

### PR DESCRIPTION
**Pull request by tyrothalos**
Someone probably needs to check this on their own test server to make sure nothing broke. That shouldn't be the case, but just to be safe. I would, but I can't set up a database server right now.

### CODE REVIEW

**Comment by rourke750** [comment]
guh laptop cant look at files changed.  I'll look into this.  What else is changed besides just maven.  A lot of file changes.

**Comment by tyrothalos** [comment]
I moved the files around a lot, but the only source code that I touched was the NMS stuff, ClassHandler.java, and AssociationListener.java. The rest should pretty much just be pom stuff.

**Comment by ProgrammerDan** [comment]
So I see no issues with this pull, although it might further delay the async PR. However, I'd honestly recommend this pull over the other, and I'd prefer to do async focusing instead of the calls that are for certain delay drivers instead of doing everything.

**Comment by ProgrammerDan** [comment]
ok to build

**Comment by Maxopoly** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ty

**Comment by Maxopoly** [comment]
http://build.civcraft.co:8080/job/NameLayer-pull/77/console

rip

**Comment by ProgrammerDan** [comment]
:-/

**Comment by tyrothalos** [comment]
What went wrong?

**Comment by ProgrammerDan** [comment]
jenkins is broken currently, looking now at fixing.

**Comment by ProgrammerDan** [comment]
retest this please

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by ProgrammerDan** [comment]
looks much better now :)  

Maven is complaining about the use of variables; this pattern was removed in Maven 4 iirc.

**Comment by tyrothalos** [comment]
I think it should be okay now.

**Comment by ProgrammerDan** [comment]
http://build.civcraft.co/job/NameLayer-pull/86/console Yep, all good.

**Comment by ProgrammerDan** [comment]
If no opposition, I'm going to merge this.

**Comment by Maxopoly** [comment]
This should not be merged without a fix for preexisting groups with pipes

**Comment by Maxopoly** [comment]
No opposition from my side

**Comment by ProgrammerDan** [comment]
Done.

**Pull request merged**
