### PR TITLE
Fix issue #62 remove original owner

### PR DESCRIPTION
**Pull request by jjj5311**
Removes original owner from group after transfer

### CODE REVIEW

**Comment by jjj5311** [comment]
Fix issue #62 with new playerpromote event only when player was mod or above and is moved to member or below

**Comment by jjj5311** [comment]
Tested this locally and it works

**Comment by rourke750** [comment]
What's the event for?

**Comment by jjj5311** [comment]
so citadel can reset their fortification status. I dont know if that is the
best way though

**Comment by jjj5311** [comment]
#62

**Comment by rourke750** [comment]
Just do PlayerState.getPlayer(player).
Then state.getgroup and if it equals that group reset.

**Comment by jjj5311** [comment]
Can you reset from name layer?

You can just close those pulls then

**Comment by rourke750** [comment]
Oh right this is namelayer.  Stupid email

**Pull request merged**
