### PR TITLE
Fix Citadel CTI Command for GroupID

### PR DESCRIPTION
**Pull request by jjj5311**
GroupManagerDao.java - Added in sql to get groupid by looking up by
groupname
Group.java - Added in variable for group id and method to access

### CODE REVIEW

**Comment by erocs** [comment]
Is this for https://github.com/Civcraft/Citadel/issues/89? The group_id is already available in the reinforcement record. Querying for a group_id for a group name from NameLayer might not return the actual owning group_id for the reinforcement.

**Comment by rourke750** [comment]
This issue is actually in the wrong repo. This needs to be in citadel.

**Comment by rourke750** [comment]
Wait ignore me. I'll handle all this when I get back.

**Comment by jjj5311** [comment]
it was for https://github.com/Civcraft/Citadel/issues/89  

I'll close it since it sounds like this info is already somewhere else

**Pull request closed without merging**
